Ryan/update and add creatable options
entelo/react-select pull request #3
Opened 2017-06-29 17:54 UTC by ryanabooth

Adding a second newOptionCreator so that we can pass in two different options when a user types something unique.

`src/Creatable.js` is the precompliation source file that contains the main changes.
`lib/Creatable.js` is the compiled version
`examples/src/components/Creatable.js` is the example on the doc page that's useful for testing / demoing the change.

The rest of the files were compiled by running `npm run build`.

https://app.asana.com/0/281605278266465/374433993661621/f

2017-06-29 19:24 UTC, vladtsf approved these changes
![image](https://user-images.githubusercontent.com/832496/27706278-e00bf996-5cc5-11e7-9aed-9555f4fb79c6.png)

2017-06-29 22:37 UTC, jmondo reviewed
gonna need to go over this together i'm super confused

2017-06-29 22:37 UTC, jmondo commented on dist/react-select.js
> +		var useSecondaryCreator = arguments.length <= 0 || arguments[0] === undefined ? false : arguments[0];
not following

2017-06-29 22:37 UTC, jmondo commented on dist/react-select.js
> +		var creator = useSecondaryCreator ? newOptionCreator2 : newOptionCreator;
should be consistent. is it secondary or 2

2017-06-29 22:37 UTC, jmondo commented on dist/react-select.js
> +		var _props5 = this.props;
omg this lib is out of control

2017-06-29 22:55 UTC, ryanabooth commented
@jmondo you reviewed the compiled code

2017-06-30 16:13 UTC, adeeb1 commented on examples/dist/bundle.js
> +		if (focusedOption && (focusedOption === this._createPlaceholderOption || this._createPlaceholderOption2 && focusedOption === this._createPlaceholderOption2) && shouldKeyDownEventCreateNewOption({ k
Wrap the new logical operators in parenthesis so your intention is clear.

2017-06-30 16:13 UTC, adeeb1 commented on examples/dist/bundle.js
> +		if (option === this._createPlaceholderOption || this._createPlaceholderOption2 && option === this._createPlaceholderOption2) {
Same here with the logical operators.

2017-06-30 16:15 UTC, adeeb1 commented on examples/dist/standalone.js
> +		if (focusedOption && (focusedOption === this._createPlaceholderOption || this._createPlaceholderOption2 && focusedOption === this._createPlaceholderOption2) && shouldKeyDownEventCreateNewOption({ k
Same here with the logical operators.

2017-06-30 16:21 UTC, adeeb1 requested changes
Looks good aside from some logical operators in all lines similar to this:

`(option === this._createPlaceholderOption || this._createPlaceholderOption2 && option === this._createPlaceholderOption2)`

Wrap in parenthesis the logical operators that should be evaluated together.

2017-06-30 17:57 UTC, adeeb1 approved these changes
Looks good! I unknowingly commented on the generated files, not the source files.

2017-06-30 19:19 UTC, merged